export enum EventType {
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  MESSAGE_PARSED = 'MESSAGE_PARSED',
  TRANSFORMATION_APPLIED = 'TRANSFORMATION_APPLIED',
  ROUTE_EVALUATED = 'ROUTE_EVALUATED',
  MESSAGE_MAPPED = 'MESSAGE_MAPPED',
  MESSAGE_SENT = 'MESSAGE_SENT',
  ACKNOWLEDGEMENT_RECEIVED = 'ACKNOWLEDGEMENT_RECEIVED',
  ERROR_OCCURRED = 'ERROR_OCCURRED',
}
